title = "PENGUINSAN"
baseURL = "https://penguinsan.netlify.com/"
languageCode = "ja"
theme = "ananke"
# canonifyurls = true # 相対パスではなく baseurl を基点とした絶対パスにする
# themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
#googleAnalytics = ""
#enableRobotsTXT = true

[sitemap]
  # changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  env = "production"
  favicon = "https://penguinsan.netlify.com/images/penguin.png"
  description = "PENGUINSAN WEBSITE"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/paris.jpg"
  recent_posts_number = 2